# Generated by Django 6.0.7 on 2026-09-29 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nombre', models.CharField(blank=True, default='', max_length=150)),
                ('accion', models.CharField(max_length=30)),
                ('objeto', models.CharField(max_length=30)),
                ('objeto_id', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('cambios', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('momento', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacora', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de bitácora',
                'verbose_name_plural': 'Bitácora',
                'ordering': ['-momento'],
            },
        ),
    ]
