# Generated by Django 6.0.7 on 2026-08-18 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planteles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('hostname', models.GenericIPAddressField(unique=True)),
                ('rol', models.CharField(choices=[('core', 'Core'), ('distribution', 'Distribución'), ('access', 'Acceso')], default='access', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('plantel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='switches', to='planteles.plantel')),
            ],
            options={
                'verbose_name': 'Switch',
                'verbose_name_plural': 'Switches',
                'ordering': ['plantel', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Puerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('indice', models.IntegerField()),
                ('estado', models.CharField(choices=[('verde', 'Uso general'), ('rojo', 'Dañado'), ('naranja', 'Trunk'), ('amarillo', 'AP Native VLAN'), ('azul', 'Telefonía'), ('gris', 'Desconectado')], default='gris', max_length=20)),
                ('vlan', models.IntegerField(blank=True, null=True)),
                ('voice_vlan', models.IntegerField(blank=True, null=True)),
                ('es_trunk', models.BooleanField(default=False)),
                ('errores_entrada', models.BigIntegerField(default=0)),
                ('errores_salida', models.BigIntegerField(default=0)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puertos', to='switches.switch')),
            ],
            options={
                'verbose_name': 'Puerto',
                'verbose_name_plural': 'Puertos',
                'ordering': ['indice'],
                'unique_together': {('switch', 'indice')},
            },
        ),
    ]
