# Generated by Django 6.0.7 on 2026-09-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puerto',
            name='errores_crc',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='puerto',
            name='estado_operativo',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='switch',
            name='cpu_1m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='cpu_5m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='cpu_5s',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='lectura_correcta',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='ultima_consulta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='puerto',
            name='errores_entrada',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='puerto',
            name='errores_salida',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
