# Generated by Django 6.0.7 on 2026-09-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0002_puerto_errores_crc_puerto_estado_operativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='puerto',
            name='dhcp',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='puerto',
            name='ip_equipo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='puerto',
            name='mac_equipo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='puerto',
            name='mac_telefono',
            field=models.TextField(blank=True, null=True),
        ),
    ]
