# Generated by Django 6.0.7 on 2026-09-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0003_puerto_dhcp_puerto_ip_equipo_puerto_mac_equipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='firmware',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
