# Generated by Django 6.0.7 on 2026-09-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0008_remove_puerto_trafico_bps'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='memoria_total_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='memoria_usada_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='memoria_usada_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='ultimo_reinicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='uptime_segundos',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
