# Generated by Django 6.0.7 on 2026-09-29 15:16

from django.db import migrations, models


def mark_physical_ports(apps, schema_editor):
    # Calcula es_fisico para los puertos existentes con la misma regla del worker.
    from switches.interfaces import is_physical_interface
    Puerto = apps.get_model('switches', 'Puerto')
    logical = [port.pk for port in Puerto.objects.only('pk', 'nombre') if not is_physical_interface(port.nombre)]
    Puerto.objects.filter(pk__in=logical).update(es_fisico=False)


def default_thresholds(apps, schema_editor):
    UmbralRol = apps.get_model('switches', 'UmbralRol')
    for rol in ('core', 'distribution', 'access'):
        UmbralRol.objects.get_or_create(rol=rol)


class Migration(migrations.Migration):

    dependencies = [
        ("switches", "0009_switch_memoria_total_bytes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UmbralRol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("core", "Core"),
                            ("distribution", "Distribución"),
                            ("access", "Acceso"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("cpu_atencion", models.PositiveSmallIntegerField(default=70)),
                ("cpu_riesgo", models.PositiveSmallIntegerField(default=90)),
                ("memoria_atencion", models.PositiveSmallIntegerField(default=80)),
                ("memoria_riesgo", models.PositiveSmallIntegerField(default=90)),
            ],
            options={
                "verbose_name": "Umbral por rol",
                "verbose_name_plural": "Umbrales por rol",
            },
        ),
        migrations.AddField(
            model_name="puerto",
            name="errores_nuevos",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="puerto",
            name="es_fisico",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="puerto",
            name="ultimo_error",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="switch",
            name="alerta_enviada",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="switch",
            name="nivel_alerta",
            field=models.CharField(default="ok", max_length=10),
        ),
        migrations.RunPython(mark_physical_ports, migrations.RunPython.noop),
        migrations.RunPython(default_thresholds, migrations.RunPython.noop),
    ]
