# Generated by Django 6.0.7 on 2026-09-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0010_salud_alertas_errores'),
    ]

    operations = [
        migrations.CreateModel(
            name='UmbralOptico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rx_atencion', models.FloatField(default=-17.0, help_text='RX (dBm) por debajo: atención')),
                ('rx_riesgo', models.FloatField(default=-20.0, help_text='RX (dBm) por debajo: en riesgo')),
                ('rx_saturacion', models.FloatField(default=0.0, help_text='RX (dBm) por encima: receptor saturado')),
                ('tx_minimo', models.FloatField(default=-9.5, help_text='TX (dBm) por debajo: láser débil')),
                ('temp_atencion', models.FloatField(default=65.0, help_text='Temperatura (°C) para atención')),
                ('temp_riesgo', models.FloatField(default=75.0, help_text='Temperatura (°C) en riesgo')),
                ('caida_rx', models.FloatField(default=3.0, help_text='dB de caída de RX en 24 h que se consideran degradación')),
            ],
            options={
                'verbose_name': 'Umbral óptico',
                'verbose_name_plural': 'Umbrales ópticos',
            },
        ),
    ]
