# Generated by Django 6.0.7 on 2026-09-29 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0011_umbral_optico'),
    ]

    operations = [
        migrations.AddField(
            model_name='puerto',
            name='bps_entrada',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='puerto',
            name='bps_salida',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='puerto',
            name='poe_estado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='puerto',
            name='poe_mw',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='puerto',
            name='ultimo_activo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='puerto',
            name='ultimo_cambio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='puerto',
            name='uso_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='puerto',
            name='vecino_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='puerto',
            name='vecino_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='puerto',
            name='vecino_plataforma',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='puerto',
            name='vecino_puerto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='puerto',
            name='velocidad_mbps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='hardware',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='poe_consumo_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='poe_presupuesto_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='temperatura_c',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EventoPuerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=20)),
                ('momento', models.DateTimeField(db_index=True)),
                ('puerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='switches.puerto')),
            ],
            options={
                'verbose_name': 'Evento de puerto',
                'verbose_name_plural': 'Eventos de puerto',
                'ordering': ['-momento'],
            },
        ),
    ]
