# Generated by Django 6.0.7 on 2026-09-29 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planteles', '0001_initial'),
        ('switches', '0012_puertos_vecinos_poe_hardware'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(default='critical', max_length=10)),
                ('motivos', models.JSONField(blank=True, default=list)),
                ('inicio', models.DateTimeField(db_index=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('notificada', models.BooleanField(default=False)),
                ('en_mantenimiento', models.BooleanField(default=False)),
                ('reconocida_en', models.DateTimeField(blank=True, null=True)),
                ('nota', models.TextField(blank=True, default='')),
                ('reconocida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_reconocidas', to=settings.AUTH_USER_MODEL)),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='switches.switch')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('motivo', models.CharField(max_length=255)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos', to=settings.AUTH_USER_MODEL)),
                ('plantel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='planteles.plantel')),
                ('switch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='switches.switch')),
            ],
            options={
                'verbose_name': 'Ventana de mantenimiento',
                'verbose_name_plural': 'Ventanas de mantenimiento',
                'ordering': ['-inicio'],
            },
        ),
    ]
