# Generated by Django 6.0.7 on 2026-09-29 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0013_alerta_mantenimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descubierto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('nombre', models.CharField(blank=True, default='', max_length=255)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('plataforma', models.CharField(blank=True, default='', max_length=255)),
                ('origen', models.CharField(choices=[('cdp', 'Vecino CDP'), ('barrido', 'Barrido SNMP')], max_length=10)),
                ('visto_desde', models.CharField(blank=True, default='', max_length=255)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('ignorado', 'Ignorado'), ('agregado', 'Agregado')], default='pendiente', max_length=10)),
                ('primera_vez', models.DateTimeField()),
                ('ultima_vez', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Equipo descubierto',
                'verbose_name_plural': 'Equipos descubiertos',
                'ordering': ['-ultima_vez'],
            },
        ),
        migrations.CreateModel(
            name='Respaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momento', models.DateTimeField(db_index=True)),
                ('verificado', models.DateTimeField(blank=True, null=True)),
                ('exito', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True, default='')),
                ('contenido', models.TextField(blank=True, default='')),
                ('hash', models.CharField(blank=True, default='', max_length=64)),
                ('lineas_agregadas', models.IntegerField(default=0)),
                ('lineas_eliminadas', models.IntegerField(default=0)),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respaldos', to='switches.switch')),
            ],
            options={
                'verbose_name': 'Respaldo de configuración',
                'verbose_name_plural': 'Respaldos de configuración',
                'ordering': ['-momento'],
            },
        ),
    ]
