# Generated by Django 6.0.7 on 2026-09-29 21:59

from django.db import migrations, models

# Un core caído se escala antes que un switch de acceso (editable en el admin).
ESCALATION_BY_ROLE = {'core': 15, 'distribution': 30, 'access': 60}


def escalation_by_role(apps, schema_editor):
    UmbralRol = apps.get_model('switches', 'UmbralRol')
    for rol, minutes in ESCALATION_BY_ROLE.items():
        UmbralRol.objects.filter(rol=rol).update(escalar_minutos=minutes)


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0014_descubiertos_respaldos'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='escalada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='umbralrol',
            name='escalar_minutos',
            field=models.PositiveSmallIntegerField(default=30, help_text='Minutos en riesgo sin reconocer antes de escalar la alerta (0 = no escalar)'),
        ),
        migrations.AddField(
            model_name='umbralrol',
            name='puertos_riesgo',
            field=models.PositiveSmallIntegerField(default=3, help_text='Puertos con errores o inestables a la vez que ponen el switch en riesgo (0 = desactivado)'),
        ),
        migrations.RunPython(escalation_by_role, migrations.RunPython.noop),
    ]
