# Generated by Django 6.0.7 on 2026-09-29 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("switches", "0015_alertas_compuestas_escalamiento"),
    ]

    operations = [
        migrations.AddField(
            model_name="puerto",
            name="vecino_tipo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("switch", "Switch"),
                    ("router", "Router"),
                    ("ap", "Access point"),
                    ("telefono", "Teléfono IP"),
                    ("otro", "Otro"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
