# Generated by Django 6.0.7 on 2026-09-29 22:53

from django.db import migrations, models

OLD_DEFAULTS = dict(rx_atencion=-17.0, rx_riesgo=-20.0, temp_atencion=65.0, caida_rx=3.0)
NEW_DEFAULTS = dict(rx_atencion=-14.0, rx_riesgo=-17.0, temp_atencion=70.0, caida_rx=2.0)


def new_defaults(apps, schema_editor):
    """Sólo la fila que nadie editó (sigue con los valores de fábrica anteriores)."""
    apps.get_model('switches', 'UmbralOptico').objects.filter(**OLD_DEFAULTS).update(**NEW_DEFAULTS)


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0016_puerto_vecino_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='puerto',
            name='optica',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='umbraloptico',
            name='caida_rx',
            field=models.FloatField(default=2.0, help_text='dB de caída de RX frente a su línea base de 7 días que se consideran degradación'),
        ),
        migrations.AlterField(
            model_name='umbraloptico',
            name='rx_atencion',
            field=models.FloatField(default=-14.0, help_text='RX (dBm) por debajo: atención'),
        ),
        migrations.AlterField(
            model_name='umbraloptico',
            name='rx_riesgo',
            field=models.FloatField(default=-17.0, help_text='RX (dBm) por debajo: en riesgo'),
        ),
        migrations.AlterField(
            model_name='umbraloptico',
            name='temp_atencion',
            field=models.FloatField(default=70.0, help_text='Temperatura (°C) para atención'),
        ),
        migrations.RunPython(new_defaults, migrations.RunPython.noop),
    ]
